### PR TITLE
fix: changes how text segments are extracted

### PR DESCRIPTION
**Pull request by rajatgupta143**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-documentai/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by rajatgupta143** [comment]
@googlebot I signed it!

**Comment by rajatgupta143** [comment]
@googlebot I signed it!

**Comment by telpirion** [comment]
Hello @rajatgupta143 , would you please do a `git commit --amend` to change your commit title? I would change it to match the pull request title `fix: changes how text segments are extracted`.

**Comment by parthea** [comment]
Closing as this is obsolete. See Issue #53 and the fix PR #56.

**Pull request closed without merging**
