### PR TITLE
samples: migrate v1beta2 doc AI samples

### PR DESCRIPTION
**Pull request by munkhuushmgl**
Samples from https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/document/cloud-client

### CODE REVIEW

**Comment by munkhuushmgl** [comment]
PTAL @engelke @telpirion

**Comment by tmatsuo** [comment]
@munkhuushmgl 

re: snippet-bot comment

The bot thinks that, the region tag prefix for documentai is `duai`. This is configured so in our internal devrel service.
Do you know which is the correct one, `documentai` or `duai`?

**Comment by munkhuushmgl** [comment]
> documentai

documentai

**Review by telpirion — COMMENTED** [review]
To make it clear which sample is which, please update all of the v1beta2 samples so that the filename includes the version, e.g.

+ batch_parse_form_v1beta2.py
+ batch_parse_table_v1beta2.py
+ etc.

**Review by telpirion — APPROVED** [review]

**Review by engelke — APPROVED** [review]
LGTM

**Pull request merged**
